const quotes = [
	"👏 You did a thing. And that's a win.",
	"Honestly, that's more than I expected. Good job.",
	"You're alive. You clicked. That counts.",
	"Productivity? Maybe not. But existence? ✅",
	"You didn't implode. We count that.",
	"That task was scared of you.",
	"Hero points awarded. Barely.",
	"You qualify as 'not a mess'. Celebrate.",
	"You're not soaring, but you're gliding. We love that.",
	"The bar is low. You cleared it. Nice.",
	"Bare minimum? Bare legend.",
	"You moved. Slightly. That's enough.",
	"Most people just scrolled today. You clicked. Respect.",
	"Minimal effort. Maximal vibes.",
	"You're not lazy, you're strategically underperforming.",
	"Big shoutout to your executive function.",
	"Did you crush it? No. But you didn't get crushed. Same thing.",
	"Barely awake, barely heroic, but still doing it.",
	"Consistency over intensity. You nailed the 'barely' part.",
	"Somewhere, someone gave up. You didn't. Gold star.",
	"You're the CEO of Showing Up.",
	"This button thinks you're amazing. And it's never wrong.",
	"One step closer to not quitting.",
	"You've achieved Mild Greatness™.",
	"We stan low-stakes champions.",
	"Productivity isn't linear. It's this. Whatever this is.",
	"You clicked. Now go lie down. You earned it.",
	"No pressure, but you're crushing the low bar.",
	"Everyone starts somewhere. You started today. Again.",
	"Remember: 'Done' is sexier than 'perfect'. You win."
];

export default quotes; 