const quotes = [
	"👏 You did a thing. And that's a win.",
	"Honestly, that's more than I expected. Good job.",
	"You're alive. You clicked. That counts.",
	"Productivity? Maybe not. But existence? ✅",
	"You didn't implode. We count that.",
	"That task was scared of you.",
	"Hero points awarded. Barely.",
	"You qualify as 'not a mess'. Celebrate.",
	"You're not soaring, but you're gliding. We love that.",
	"The bar is low. You cleared it. Nice.",
	"Bare minimum? Bare legend.",
	"You moved. Slightly. That's enough.",
	"Most people just scrolled today. You clicked. Respect.",
	"Minimal effort. Maximal vibes.",
	"You're not lazy, you're strategically underperforming.",
	"Big shoutout to your executive function.",
	"Did you crush it? No. But you didn't get crushed. Same thing.",
	"Barely awake, barely heroic, but still doing it.",
	"Consistency over intensity. You nailed the 'barely' part.",
	"Somewhere, someone gave up. You didn't. Gold star.",
	"You're the CEO of Showing Up.",
	"This button thinks you're amazing. And it's never wrong.",
	"One step closer to not quitting.",
	"You've achieved Mild Greatness™.",
	"We stan low-stakes champions.",
	"Productivity isn't linear. It's this. Whatever this is.",
	"You clicked. Now go lie down. You earned it.",
	"No pressure, but you're crushing the low bar.",
	"Everyone starts somewhere. You started today. Again.",
	"Remember: 'Done' is sexier than 'perfect'. You win."
];

// Russian quotes
export const russianQuotes = [
	"👏 Ты сделал что-то. И этого хватит.",
	"Честно? Я ожидал меньше. Хорошая работа.",
	"Ты жив. Ты кликнул. Это считается.",
	"Продуктивность? Возможно, нет. Но существование? ✅",
	"Ты не взорвался. Мы засчитали.",
	"Задача испугалась тебя первой.",
	"Очки героя начислены. Почти.",
	"Ты подходишь под статус 'не совсем развал'. Празднуем.",
	"Ты не летаешь, но и не падаешь. Нас это устраивает.",
	"Планка была низкая. Ты её перепрыгнул. Уважение.",
	"Минимум? Легендарно.",
	"Ты пошевелился. Чуть-чуть. Уже неплохо.",
	"Большинство просто листали. А ты кликнул. Респект.",
	"Минимум усилий — максимум вайба.",
	"Ты не ленивый. Ты стратегически недорабатываешь.",
	"Огромный респект твоей функции самоуправления.",
	"Ты не разнёс день, но и день не разнёс тебя. Ничья.",
	"Полусонный, полугероический — но ты в игре.",
	"Стабильность важнее героизма. Ты стабильно на минималке.",
	"Где-то кто-то сдался. А ты — нет. Звезда тебе в лоб.",
	"Ты — CEO по появлению в своей жизни.",
	"Эта кнопка считает тебя крутым. И она никогда не ошибается.",
	"На один шаг ближе к тому, чтобы не сдаться.",
	"Ты достиг Лёгкой Великолепности™.",
	"Мы уважаем чемпионов с низкой ставкой.",
	"Продуктивность не линейна. Она вот такая. Как ты сейчас.",
	"Ты кликнул. Теперь иди полежи. Заслуженно.",
	"Без давления, но ты разнёс нижнюю границу.",
	"Все с чего-то начинают. Ты начал сегодня. Опять.",
	"'Сделано' — сексуальнее, чем 'идеально'. Ты победил."
];

export default quotes; 