// Barely Useful Tips array
export const barelyUsefulTips = [
	"💧 Drink water. You're not a plant, but close enough.",
	"📧 Replying to one email is technically communication.",
	"🛌 Lying horizontally still counts as existing.",
	"🗑️ Deleting a file = emotional release.",
	"📅 Rescheduling is just time travel for grown-ups.",
	"🧠 Thinking about working is half the battle. Maybe.",
	"😶 Ignoring Slack for 10 minutes builds character.",
	"🫠 Melting emotionally still counts as a process.",
	"🍞 Toast is a valid meal. So is air.",
	"🔌 Restarting your device is basically therapy.",
	"📦 Organizing your desktop = controlling chaos.",
	"📣 Whispering 'no' to your inbox is self-care.",
	"🐌 Slow progress is still progress. Ask a snail.",
	"📓 Unchecked boxes are just dreams in progress.",
	"🌬️ Deep sighs are unofficial breathing exercises.",
	"🥱 Yawning loudly = asserting dominance in Zoom calls.",
	"📱 Scrolling mindlessly counts as market research if you're sad.",
	"💬 You thought about journaling. That's emotional effort.",
	"🧘 Meditating for 17 seconds still counts. Technically.",
	"📦 Moving a task to tomorrow makes you a visionary.",
	"🖥️ Staring at your screen = digital mindfulness.",
	"🙃 Turning off notifications is radical rebellion.",
	"🛒 Buying snacks is emotional resource management.",
	"📸 Screenshotting your task list = progress backup.",
	"🦥 Slowness is underrated. So are sloths.",
	"🎧 Listening to lo-fi = ambient healing.",
	"🔁 Repeating mistakes = data collection.",
	"📕 Closing the laptop is setting boundaries.",
	"🚿 Shower thoughts = strategic planning.",
	"🧻 Crying in the bathroom is still movement."
]; 